import { AppointmentWithDetails } from "./scheduling-utils";

export function getDemoAppointments(selectedDate: Date) {
  return [
    // Operatory 1 - Mixed providers (Dr. Nguyen and Dr. Robert)
    {
      id: 1,
      patientId: 1,
      patient: { id: 1, firstName: "Rick", lastName: "Sanchez", avatarInitials: "RS", dateOfBirth: null, insuranceProvider: "Delta Dental", allergies: null, balanceDue: 0 },
      providerId: 1, // Dr. Nguyen
      provider: { id: 1, name: "Dr. Nguyen", role: "Dentist", color: "#FF9E80" },
      operatoryId: 1,
      operatory: { id: 1, name: "Op 1", color: "#C2E0FF" },
      date: selectedDate,
      startTime: "08:00:00",
      endTime: null,
      duration: 70,
      durationMinutes: null,
      procedure: "Crown - Porcelain Fused to High Noble Metal",
      cdtCode: "D2750",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 30),
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 2,
      patientId: 2,
      patient: { id: 2, firstName: "Morty", lastName: "Smith", avatarInitials: "MS", dateOfBirth: null, insuranceProvider: "Cigna", allergies: null, balanceDue: 4500 },
      providerId: 2, // Dr. Robert
      provider: { id: 2, name: "Dr. Robert", role: "Dentist", color: "#B39DDB" },
      operatoryId: 1,
      operatory: { id: 1, name: "Op 1", color: "#C2E0FF" },
      date: selectedDate,
      startTime: "10:00:00",
      endTime: null,
      duration: 90,
      durationMinutes: null,
      procedure: "Core Buildup, Including any Pins",
      cdtCode: "D2950",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 60),
      arrivedAt: new Date(new Date().getTime() - 1000 * 60 * 45),
      chairStartedAt: new Date(new Date().getTime() - 1000 * 60 * 15),
      completedAt: null
    },
    {
      id: 5,
      patientId: 5,
      patient: { id: 5, firstName: "Summer", lastName: "Smith", avatarInitials: "SS", dateOfBirth: null, insuranceProvider: "Delta Dental", allergies: null, balanceDue: 0 },
      providerId: 1, // Dr. Nguyen
      provider: { id: 1, name: "Dr. Nguyen", role: "Dentist", color: "#FF9E80" },
      operatoryId: 1,
      operatory: { id: 1, name: "Op 1", color: "#C2E0FF" },
      date: selectedDate,
      startTime: "13:00:00",
      endTime: null,
      duration: 45,
      durationMinutes: null,
      procedure: "Periodic Oral Evaluation",
      cdtCode: "D0120",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 6,
      patientId: 6,
      patient: { id: 6, firstName: "Beth", lastName: "Smith", avatarInitials: "BS", dateOfBirth: null, insuranceProvider: "Guardian", allergies: null, balanceDue: 0 },
      providerId: 2, // Dr. Robert
      provider: { id: 2, name: "Dr. Robert", role: "Dentist", color: "#B39DDB" },
      operatoryId: 1,
      operatory: { id: 1, name: "Op 1", color: "#C2E0FF" },
      date: selectedDate,
      startTime: "14:30:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Resin-Based Composite - Three Surfaces",
      cdtCode: "D2332",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    
    // Operatory 2 - Mixed providers (Dr. Johnson and Dr. Maria)
    {
      id: 3,
      patientId: 3,
      patient: { id: 3, firstName: "David", lastName: "Lee", avatarInitials: "DL", dateOfBirth: null, insuranceProvider: "Aetna", allergies: null, balanceDue: 0 },
      providerId: 4, // Dr. Maria
      provider: { id: 4, name: "Dr. Maria", role: "Dentist", color: "#C5E1A5" },
      operatoryId: 2,
      operatory: { id: 2, name: "Op 2", color: "#FFD6D6" },
      date: selectedDate,
      startTime: "08:30:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Resin-Based Composite - One Surface",
      cdtCode: "D2330",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 8,
      patientId: 8,
      patient: { id: 8, firstName: "Emily", lastName: "Davis", avatarInitials: "ED", dateOfBirth: null, insuranceProvider: "Humana", allergies: null, balanceDue: 1200 },
      providerId: 3, // Dr. Johnson
      provider: { id: 3, name: "Dr. Johnson", role: "Dentist", color: "#90CAF9" },
      operatoryId: 2,
      operatory: { id: 2, name: "Op 2", color: "#FFD6D6" },
      date: selectedDate,
      startTime: "10:15:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Extraction - Single Tooth",
      cdtCode: "D7140",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 13,
      patientId: 13,
      patient: { id: 13, firstName: "Benjamin", lastName: "Jackson", avatarInitials: "BJ", dateOfBirth: null, insuranceProvider: "MetLife", allergies: null, balanceDue: 750 },
      providerId: 4, // Dr. Maria
      provider: { id: 4, name: "Dr. Maria", role: "Dentist", color: "#C5E1A5" },
      operatoryId: 2,
      operatory: { id: 2, name: "Op 2", color: "#FFD6D6" },
      date: selectedDate,
      startTime: "12:00:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Amalgam - One Surface",
      cdtCode: "D2140",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 9,
      patientId: 9,
      patient: { id: 9, firstName: "James", lastName: "Miller", avatarInitials: "JM", dateOfBirth: null, insuranceProvider: "UnitedHealthcare", allergies: null, balanceDue: 0 },
      providerId: 3, // Dr. Johnson
      provider: { id: 3, name: "Dr. Johnson", role: "Dentist", color: "#90CAF9" },
      operatoryId: 2,
      operatory: { id: 2, name: "Op 2", color: "#FFD6D6" },
      date: selectedDate,
      startTime: "13:30:00",
      endTime: null,
      duration: 90,
      durationMinutes: null,
      procedure: "Root Canal - Molar",
      cdtCode: "D3330",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 14,
      patientId: 14,
      patient: { id: 14, firstName: "Ava", lastName: "White", avatarInitials: "AW", dateOfBirth: null, insuranceProvider: "Guardian", allergies: null, balanceDue: 0 },
      providerId: 4, // Dr. Maria
      provider: { id: 4, name: "Dr. Maria", role: "Dentist", color: "#C5E1A5" },
      operatoryId: 2,
      operatory: { id: 2, name: "Op 2", color: "#FFD6D6" },
      date: selectedDate,
      startTime: "15:30:00",
      endTime: null,
      duration: 30,
      durationMinutes: null,
      procedure: "Bitewing X-rays",
      cdtCode: "D0274",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 22,
      patientId: 22,
      patient: { id: 22, firstName: "D'Vana", lastName: "Tendi", avatarInitials: "DT", dateOfBirth: null, insuranceProvider: "Aetna", allergies: null, balanceDue: 325 },
      providerId: 2, // Dr. Robert
      provider: { id: 2, name: "Dr. Robert", role: "Dentist", color: "#B39DDB" },
      operatoryId: 2,
      operatory: { id: 2, name: "Op 2", color: "#FFD6D6" },
      date: selectedDate,
      startTime: "16:30:00",
      endTime: null,
      duration: 30,
      durationMinutes: null,
      procedure: "Periodic Oral Evaluation",
      cdtCode: "D0120",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 40),
      arrivedAt: new Date(new Date().getTime() - 1000 * 60 * 15),
      chairStartedAt: null,
      completedAt: null,
      status: "checked_in"
    },
    
    // Operatory 3 - Mixed providers (Dr. Nguyen and Dr. Johnson)
    {
      id: 4,
      patientId: 4,
      patient: { id: 4, firstName: "Sarah", lastName: "Martinez", avatarInitials: "SM", dateOfBirth: null, insuranceProvider: "MetLife", allergies: null, balanceDue: 2000 },
      providerId: 1, // Dr. Nguyen
      provider: { id: 1, name: "Dr. Nguyen", role: "Dentist", color: "#FF9E80" },
      operatoryId: 3,
      operatory: { id: 3, name: "Op 3", color: "#D7CCC8" },
      date: selectedDate,
      startTime: "08:00:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Prophylaxis - Adult",
      cdtCode: "D1110",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 60),
      arrivedAt: new Date(new Date().getTime() - 1000 * 60 * 10),
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 10,
      patientId: 10,
      patient: { id: 10, firstName: "Sophia", lastName: "Wilson", avatarInitials: "SW", dateOfBirth: null, insuranceProvider: "Aetna", allergies: null, balanceDue: 350 },
      providerId: 3, // Dr. Johnson
      provider: { id: 3, name: "Dr. Johnson", role: "Dentist", color: "#90CAF9" },
      operatoryId: 3,
      operatory: { id: 3, name: "Op 3", color: "#D7CCC8" },
      date: selectedDate,
      startTime: "09:30:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Prophylaxis - Adult",
      cdtCode: "D1110",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 7,
      patientId: 7,
      patient: { id: 7, firstName: "Michael", lastName: "Brown", avatarInitials: "MB", dateOfBirth: null, insuranceProvider: "MetLife", allergies: null, balanceDue: 25000 },
      providerId: 1, // Dr. Nguyen
      provider: { id: 1, name: "Dr. Nguyen", role: "Dentist", color: "#FF9E80" },
      operatoryId: 3,
      operatory: { id: 3, name: "Op 3", color: "#D7CCC8" },
      date: selectedDate,
      startTime: "11:00:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Resin-Based Composite - Four Surfaces",
      cdtCode: "D2335",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 90),
      arrivedAt: new Date(new Date().getTime() - 1000 * 60 * 75),
      chairStartedAt: new Date(new Date().getTime() - 1000 * 60 * 60),
      completedAt: new Date(new Date().getTime() - 1000 * 60 * 5)
    },
    {
      id: 11,
      patientId: 11,
      patient: { id: 11, firstName: "Beckett", lastName: "Mariner", avatarInitials: "BM", dateOfBirth: null, insuranceProvider: "BlueCross", allergies: null, balanceDue: 800 },
      providerId: 3, // Dr. Johnson
      provider: { id: 3, name: "Dr. Johnson", role: "Dentist", color: "#90CAF9" },
      operatoryId: 3,
      operatory: { id: 3, name: "Op 3", color: "#D7CCC8" },
      date: selectedDate,
      startTime: "13:00:00",
      endTime: null,
      duration: 45,
      durationMinutes: null,
      procedure: "Comprehensive Oral Evaluation",
      cdtCode: "D0150",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 20),
      arrivedAt: new Date(new Date().getTime() - 1000 * 60 * 10),
      chairStartedAt: new Date(),
      completedAt: null,
      status: "in_chair"
    },
    {
      id: 15,
      patientId: 15,
      patient: { id: 15, firstName: "Lucas", lastName: "Harris", avatarInitials: "LH", dateOfBirth: null, insuranceProvider: "Humana", allergies: null, balanceDue: 0 },
      providerId: 4, // Dr. Maria
      provider: { id: 4, name: "Dr. Maria", role: "Dentist", color: "#C5E1A5" },
      operatoryId: 3,
      operatory: { id: 3, name: "Op 3", color: "#D7CCC8" },
      date: selectedDate,
      startTime: "15:00:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Crown Prep",
      cdtCode: "D2740",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 23,
      patientId: 23,
      patient: { id: 23, firstName: "Sam", lastName: "Rutherford", avatarInitials: "SR", dateOfBirth: null, insuranceProvider: "MetLife", allergies: null, balanceDue: 150 },
      providerId: 3, // Dr. Johnson
      provider: { id: 3, name: "Dr. Johnson", role: "Dentist", color: "#90CAF9" },
      operatoryId: 3,
      operatory: { id: 3, name: "Op 3", color: "#D7CCC8" },
      date: selectedDate,
      startTime: "16:30:00",
      endTime: null,
      duration: 30,
      durationMinutes: null,
      procedure: "Limited Oral Evaluation",
      cdtCode: "D0140",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 35),
      arrivedAt: new Date(new Date().getTime() - 1000 * 60 * 10),
      chairStartedAt: null,
      completedAt: null,
      status: "checked_in"
    },
    
    // Operatory 4 - Mixed providers (Dr. Robert and Dr. Maria)
    {
      id: 17,
      patientId: 17,
      patient: { id: 17, firstName: "Ethan", lastName: "Thompson", avatarInitials: "ET", dateOfBirth: null, insuranceProvider: "Aetna", allergies: null, balanceDue: 200 },
      providerId: 2, // Dr. Robert
      provider: { id: 2, name: "Dr. Robert", role: "Dentist", color: "#B39DDB" },
      operatoryId: 4,
      operatory: { id: 4, name: "Op 4", color: "#D6EEDA" },
      date: selectedDate,
      startTime: "08:00:00",
      endTime: null,
      duration: 45,
      durationMinutes: null,
      procedure: "Limited Oral Evaluation",
      cdtCode: "D0140",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 16,
      patientId: 16,
      patient: { id: 16, firstName: "Mia", lastName: "Martin", avatarInitials: "MM", dateOfBirth: null, insuranceProvider: "Delta Dental", allergies: null, balanceDue: 1500 },
      providerId: 4, // Dr. Maria
      provider: { id: 4, name: "Dr. Maria", role: "Dentist", color: "#C5E1A5" },
      operatoryId: 4,
      operatory: { id: 4, name: "Op 4", color: "#D6EEDA" },
      date: selectedDate,
      startTime: "09:15:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Periodontal Maintenance",
      cdtCode: "D4910",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 18,
      patientId: 18,
      patient: { id: 18, firstName: "Isabella", lastName: "Garcia", avatarInitials: "IG", dateOfBirth: null, insuranceProvider: "Cigna", allergies: null, balanceDue: 0 },
      providerId: 2, // Dr. Robert
      provider: { id: 2, name: "Dr. Robert", role: "Dentist", color: "#B39DDB" },
      operatoryId: 4,
      operatory: { id: 4, name: "Op 4", color: "#D6EEDA" },
      date: selectedDate,
      startTime: "11:00:00",
      endTime: null,
      duration: 75,
      durationMinutes: null,
      procedure: "Comprehensive Periodontal Evaluation",
      cdtCode: "D0180",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 21,
      patientId: 21,
      patient: { id: 21, firstName: "Bradward", lastName: "Boimler", avatarInitials: "BB", dateOfBirth: null, insuranceProvider: "Delta Dental", allergies: null, balanceDue: 750 },
      providerId: 4, // Dr. Maria
      provider: { id: 4, name: "Dr. Maria", role: "Dentist", color: "#C5E1A5" },
      operatoryId: 4,
      operatory: { id: 4, name: "Op 4", color: "#D6EEDA" },
      date: selectedDate,
      startTime: "13:00:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Root Canal - Anterior",
      cdtCode: "D3310",
      isVerified: null,
      confirmedAt: new Date(new Date().getTime() - 1000 * 60 * 30),
      arrivedAt: new Date(new Date().getTime() - 1000 * 60 * 20),
      chairStartedAt: new Date(new Date().getTime() - 1000 * 60 * 5),
      completedAt: null,
      status: "in_chair"
    },
    {
      id: 19,
      patientId: 19,
      patient: { id: 19, firstName: "Mason", lastName: "Martinez", avatarInitials: "MM", dateOfBirth: null, insuranceProvider: "MetLife", allergies: null, balanceDue: 0 },
      providerId: 2, // Dr. Robert
      provider: { id: 2, name: "Dr. Robert", role: "Dentist", color: "#B39DDB" },
      operatoryId: 4,
      operatory: { id: 4, name: "Op 4", color: "#D6EEDA" },
      date: selectedDate,
      startTime: "15:00:00",
      endTime: null,
      duration: 60,
      durationMinutes: null,
      procedure: "Full Mouth X-ray",
      cdtCode: "D0210",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null
    },
    {
      id: 20,
      patientId: 20,
      patient: { id: 20, firstName: "Charlotte", lastName: "Robinson", avatarInitials: "CR", dateOfBirth: null, insuranceProvider: "BlueCross", allergies: null, balanceDue: 0 },
      providerId: 1, // Dr. Nguyen
      provider: { id: 1, name: "Dr. Nguyen", role: "Dentist", color: "#FF9E80" },
      operatoryId: 1,
      operatory: { id: 1, name: "Op 1", color: "#C2E0FF" },
      date: selectedDate,
      startTime: "16:30:00",
      endTime: null,
      duration: 30,
      durationMinutes: null,
      procedure: "Bitewing X-rays",
      cdtCode: "D0274",
      isVerified: null,
      confirmedAt: null,
      arrivedAt: null,
      chairStartedAt: null,
      completedAt: null,
      status: "unconfirmed"
    }
  ] as AppointmentWithDetails[];
}