import { ActionItem, DashboardData, FlowCategory, KPI, UserRole, WinItem } from './types';
import { format } from 'date-fns';

const today = new Date();
const formattedDate = format(today, 'EEEE, MMMM do');
const currentHour = today.getHours();

let timeOfDay = 'day';
if (currentHour < 12) {
  timeOfDay = 'morning';
} else if (currentHour < 17) {
  timeOfDay = 'afternoon';
} else {
  timeOfDay = 'evening';
}

// Front Office Mock Data
const frontOfficeData: DashboardData = {
  greeting: `Good morning, Maria`,
  greetingDetails: "AI cleared 2 wait-list gaps overnight; let's keep the chairs spinning.",
  kpis: [
    {
      label: 'Patients Confirmed',
      value: 14,
      target: 18,
      status: 'warning',
      trend: 'up',
      successMessage: 'Fully confirmed — heroic!',
    },
    {
      label: 'Insurances Verified',
      value: 10,
      target: 12,
      status: 'success',
      trend: 'up',
      successMessage: 'Zero surprises inbound.',
    },
    {
      label: 'Recall Slots Filled',
      value: 3,
      target: 6,
      status: 'neutral',
      trend: 'neutral',
      successMessage: 'Hygiene schedule solid.',
    },
  ],
  actionItems: [
    {
      id: '1',
      priority: 1,
      type: 'form',
      title: 'Verify eligibility — Jacob Lee',
      description: 'New patient, Cigna PPO',
      dueIn: '80 min',
      patientId: 101,
      patientName: 'Jacob Lee',
      completed: false,
      icon: 'FileText',
      estimatedTimeMin: 5,
    },
    {
      id: '2',
      priority: 2,
      type: 'document',
      title: 'Request missing X-ray — Sarah Johnson',
      description: 'Crown seat Thursday',
      dueIn: '165 min',
      patientId: 104,
      patientName: 'Sarah Johnson',
      completed: false,
      icon: 'FileX',
      estimatedTimeMin: 3,
    },
    {
      id: '3',
      priority: 3,
      type: 'reminder',
      title: 'Send recall texts',
      description: '6 hygiene patients next week',
      dueIn: '180 min',
      completed: false,
      icon: 'MessageSquare',
      estimatedTimeMin: 10,
    },
    {
      id: '4',
      priority: 4,
      type: 'call',
      title: 'Confirm lab arrival',
      description: 'Prime Dental Lab, case #8342',
      dueIn: '240 min',
      completed: false,
      icon: 'Phone',
      estimatedTimeMin: 2,
    },
    {
      id: '5',
      priority: 5,
      type: 'form',
      title: 'Order burs & paste',
      description: 'Stock ≤ 2 days',
      completed: false,
      icon: 'Package',
      estimatedTimeMin: 8,
    },
    {
      id: '6',
      priority: 6,
      type: 'document',
      title: 'Prepare deposit slip',
      description: 'Yesterday totals',
      dueIn: '240 min',
      completed: false,
      icon: 'DollarSign',
      estimatedTimeMin: 5,
    },
  ],
  flowCategories: [
    {
      id: 'checkedIn',
      label: 'Checked In',
      count: 1,
    },
    {
      id: 'seated',
      label: 'Seated',
      count: 2,
    },
    {
      id: 'readyForCheckout',
      label: 'Ready for Checkout',
      count: 0,
    },
  ],
  wins: [
    {
      id: 'win1',
      title: 'Patient confirmed',
      description: 'Maria confirmed Emily Anderson by SMS',
      timestamp: '8:07 AM',
      icon: 'CheckCircle2',
      isAi: false,
      timeSavedMin: 2,
    },
    {
      id: 'win2',
      title: 'Insurance verified',
      description: 'AI verified Cigna benefits for Michael Chen',
      timestamp: '7:55 AM',
      icon: 'FileText',
      isAi: true,
      timeSavedMin: 8,
    },
    {
      id: 'win3',
      title: 'Recalls sent',
      description: 'AI sent 12 recall reminders (3 responses so far)',
      timestamp: '7:15 AM',
      icon: 'Bell',
      isAi: true,
      timeSavedMin: 25,
    },
    {
      id: 'win4',
      title: 'Appointment filled',
      description: 'Maria rescheduled cancellation with waitlist',
      timestamp: '8:30 AM',
      icon: 'Calendar',
      isAi: false,
      timeSavedMin: 5,
    },
    {
      id: 'win5',
      title: 'Patient educated',
      description: 'Maria reassured anxious new patient',
      timestamp: '8:45 AM',
      icon: 'MessageCircle',
      isAi: false,
      timeSavedMin: 4,
    },
  ],
};

// Hygienist Mock Data
const hygienistData: DashboardData = {
  greeting: `Happy ${formattedDate}, Jasmine`,
  greetingDetails: 'You prevent gum disease in 6 patients today.',
  kpis: [
    {
      label: 'Wait-to-Seat',
      value: 7,
      target: 10,
      unit: 'min',
      status: 'success',
      trend: 'down',
    },
    {
      label: 'Pocket Depth ≤3mm',
      value: 82,
      target: 80,
      isPercentage: true,
      status: 'success',
      trend: 'up',
    },
    {
      label: 'Fluoride Acceptance',
      value: 68,
      target: 75,
      isPercentage: true,
      status: 'warning',
      trend: 'up',
    },
  ],
  actionItems: [
    {
      id: '1',
      priority: 1,
      type: 'clinical',
      title: 'Jessica Kim - overdue FMX X-rays',
      description: 'Capture pre-exam?',
      patientId: 105,
      patientName: 'Jessica Kim',
      completed: false,
      icon: 'FileX',
      estimatedTimeMin: 10,
    },
    {
      id: '2',
      priority: 2,
      type: 'clinical',
      title: 'Michael Chen - demo floss loop video',
      description: 'Shown difficulty with proper technique',
      patientId: 106,
      patientName: 'Michael Chen',
      completed: false,
      icon: 'Video',
      estimatedTimeMin: 5,
    },
    {
      id: '3',
      priority: 3,
      type: 'clinical',
      title: 'Check Perio Risk Assessment',
      description: 'For Lisa Thompson - diabetic patient',
      patientId: 107,
      patientName: 'Lisa Thompson',
      completed: false,
      icon: 'Activity',
      estimatedTimeMin: 7,
    },
    {
      id: '4',
      priority: 4,
      type: 'clinical',
      title: 'Review home care instructions',
      description: 'For David Brown - new implant patient',
      patientId: 108,
      patientName: 'David Brown',
      completed: false,
      icon: 'FileText',
      estimatedTimeMin: 4,
    },
  ],
  flowCategories: [
    {
      id: 'seated',
      label: 'Seated',
      count: 1,
    },
    {
      id: 'doctorReady',
      label: 'Doctor Ready',
      count: 2,
      isBottleneck: false,
    },
  ],
  wins: [
    {
      id: 'win1',
      title: 'Perio charts ready',
      description: 'Generated perio chart summaries',
      timestamp: '7:45 AM',
      icon: 'FileText',
      isAi: true,
      timeSavedMin: 15,
    },
    {
      id: 'win2',
      title: 'Reports generated',
      description: 'Treatment plans prepared for review',
      timestamp: '7:30 AM',
      icon: 'FileCheck',
      isAi: false,
      timeSavedMin: 4,
    },
    {
      id: 'win3',
      title: 'Patient education queued',
      description: 'Videos queued on iPad for 3 patients',
      timestamp: '7:15 AM',
      icon: 'Video',
      isAi: true,
      timeSavedMin: 6,
    },
    {
      id: 'win4',
      title: 'Periodontal insights',
      description: 'Detected 2 high-risk perio patients',
      timestamp: '8:15 AM',
      icon: 'Activity',
      isAi: true,
      timeSavedMin: 10,
    },
  ],
};

// Provider/Dentist Mock Data
const providerData: DashboardData = {
  greeting: `Good ${timeOfDay}, Dr. Patel`,
  greetingDetails: '3 crowns and 1 Invisalign consult could add $6,340 today.',
  kpis: [
    {
      label: 'Production vs Goal',
      value: 4250,
      target: 8000,
      unit: '$',
      status: 'warning',
      trend: 'up',
    },
    {
      label: 'Treatment Acceptance',
      value: 85,
      target: 80,
      isPercentage: true,
      status: 'success',
      trend: 'up',
    },
    {
      label: 'Seat-to-Doctor Avg',
      value: 5.2,
      target: 8,
      unit: 'min',
      status: 'success',
      trend: 'down',
    },
  ],
  actionItems: [
    {
      id: '1',
      priority: 1,
      type: 'clinical',
      title: 'Crown prep - Sarah Johnson',
      description: 'Seated 4 min, go now?',
      patientId: 104,
      patientName: 'Sarah Johnson',
      completed: false,
      icon: 'Tool',
    },
    {
      id: '2',
      priority: 2,
      type: 'clinical',
      title: 'Invisalign consult',
      description: 'Show simulation?',
      patientId: 109,
      patientName: 'Jennifer Davis',
      completed: false,
      icon: 'Smile',
    },
    {
      id: '3',
      priority: 3,
      type: 'document',
      title: 'Sign lab slip for UR crown',
      description: 'For Robert Garcia (#18)',
      patientId: 101,
      patientName: 'Robert Garcia',
      completed: false,
      icon: 'FileSignature',
    },
    {
      id: '4',
      priority: 4,
      type: 'clinical',
      title: 'Review pre-op X-rays',
      description: 'For extraction at 11:30 AM',
      patientId: 110,
      patientName: 'Daniel Martinez',
      completed: false,
      icon: 'FileX',
    },
  ],
  flowCategories: [
    {
      id: 'doctorReady',
      label: 'Doctor Ready',
      count: 2,
      isBottleneck: true,
    },
    {
      id: 'inTreatment',
      label: 'In Treatment',
      count: 1,
    },
  ],
  wins: [
    {
      id: 'win1',
      title: 'SOAP notes drafted',
      description: 'Drafted 4 SOAP notes for approval',
      timestamp: '7:45 AM',
      icon: 'FileText',
      isAi: true,
      savings: 25,
      timeSavedMin: 20,
    },
    {
      id: 'win2',
      title: 'Lab cases tracked',
      description: 'Crown for Moore arriving tomorrow',
      timestamp: '6:30 AM',
      icon: 'Package',
      isAi: false,
    },
    {
      id: 'win3',
      title: 'Treatment plans prepared',
      description: 'Visual aids ready for 2 presentations',
      timestamp: '6:15 AM',
      icon: 'LayoutTemplate',
      isAi: true,
      value: 5200,
    },
    {
      id: 'win4',
      title: 'Clinical insights analyzed',
      description: 'Detected inconsistent occlusion pattern',
      timestamp: '8:30 AM',
      icon: 'FileSearch',
      isAi: true,
      timeSavedMin: 12,
    },
  ],
};

// Billing Specialist Mock Data
const billingData: DashboardData = {
  greeting: `${timeOfDay === 'morning' ? 'Morning' : 'Hello'}, Liam`,
  greetingDetails: '$3,450 is one click away—AI prepared 12 claims.',
  kpis: [
    {
      label: 'Claims Pending',
      value: 24,
      target: 30,
      status: 'success',
      trend: 'down',
    },
    {
      label: 'Denial Rate',
      value: 8.5,
      target: 10,
      isPercentage: true,
      status: 'success',
      trend: 'down',
    },
    {
      label: 'A/R > 90 days',
      value: 12500,
      target: 15000,
      unit: '$',
      status: 'success',
      trend: 'down',
    },
  ],
  actionItems: [
    {
      id: '1',
      priority: 1,
      type: 'document',
      title: 'Appeal Denial A927',
      description: 'Missing X-ray - add & resubmit',
      patientId: 111,
      patientName: 'Angela White',
      completed: false,
      icon: 'AlertOctagon',
    },
    {
      id: '2',
      priority: 2,
      type: 'document',
      title: 'Post ERA 1120',
      description: '8 claims - 98% auto',
      completed: false,
      icon: 'FileCheck',
    },
    {
      id: '3',
      priority: 3,
      type: 'collection',
      title: 'Send statement',
      description: 'Robert Garcia $720 - 45 days overdue',
      amount: 720,
      patientId: 101,
      patientName: 'Robert Garcia',
      completed: false,
      icon: 'Mail',
    },
    {
      id: '4',
      priority: 4,
      type: 'collection',
      title: 'Review aging report',
      description: '5 accounts > 60 days need attention',
      completed: false,
      icon: 'Clock',
    },
  ],
  flowCategories: [
    {
      id: 'checkedOutWithBalance',
      label: 'Checked-Out (Balance > $0)',
      count: 3,
      isBottleneck: true,
    },
    {
      id: 'claimsToSubmit',
      label: 'Claims to Submit',
      count: 12,
    },
    {
      id: 'pendingInsurance',
      label: 'Pending Insurance',
      count: 24,
    },
  ],
  wins: [
    {
      id: 'win1',
      title: 'ERA posted',
      description: 'Posted $4,110 ERAs overnight',
      value: 4110,
      timestamp: '6:00 AM',
      icon: 'DollarSign',
      isAi: true,
      savings: 58,
      timeSavedMin: 35,
    },
    {
      id: 'win2',
      title: 'Claims submitted',
      description: '15 claims processed & submitted',
      timestamp: '6:30 AM',
      icon: 'Send',
      isAi: true,
      value: 3450,
      timeSavedMin: 45,
    },
    {
      id: 'win3',
      title: 'Payment collected',
      description: 'Online payment of $325 received',
      value: 325,
      timestamp: '11:00 PM (yesterday)',
      icon: 'CreditCard',
      isAi: false,
    },
    {
      id: 'win4',
      title: 'Denial predicted',
      description: 'Missing attachment flagged before submit',
      timestamp: '7:10 AM',
      icon: 'AlertTriangle',
      isAi: true,
      savings: 42,
      timeSavedMin: 18,
    },
    {
      id: 'win5',
      title: 'Patient ledger reconciled',
      description: 'Automated balancing of three accounts',
      timestamp: '4:30 AM',
      icon: 'FileCheck',
      isAi: true,
      timeSavedMin: 25,
    },
  ],
};

// Practice Owner / Manager Mock Data
const ownerData: DashboardData = {
  greeting: `Good ${timeOfDay}, Dr. Lopez`,
  greetingDetails: 'Revenue pacing +12% this month, but hygiene recall 78% (target 90%).',
  kpis: [
    {
      label: 'Revenue vs Target',
      value: 45620,
      target: 42000,
      unit: '$',
      status: 'success',
      trend: 'up',
      delta: 12,
    },
    {
      label: 'Chair Utilization',
      value: 85,
      target: 90,
      isPercentage: true,
      status: 'warning',
      trend: 'up',
    },
    {
      label: 'Recall Compliance',
      value: 78,
      target: 90,
      isPercentage: true,
      status: 'danger',
      trend: 'down',
    },
    {
      label: 'Staff Overtime',
      value: 12.5,
      target: 10,
      unit: 'hrs',
      status: 'warning',
      trend: 'up',
    },
  ],
  actionItems: [
    {
      id: '1',
      priority: 1,
      type: 'approval',
      title: 'Approve hiring requisition',
      description: 'Hygiene gaps next month',
      completed: false,
      icon: 'UserPlus',
    },
    {
      id: '2',
      priority: 2,
      type: 'document',
      title: 'Denial spike +6%',
      description: 'Review Payer Delta CA',
      completed: false,
      icon: 'TrendingUp',
    },
    {
      id: '3',
      priority: 3,
      type: 'approval',
      title: 'Review equipment proposal',
      description: 'New scanner ROI analysis',
      completed: false,
      icon: 'PackageCheck',
    },
    {
      id: '4',
      priority: 4,
      type: 'document',
      title: 'Monthly KPI review',
      description: 'Prepare for team meeting tomorrow',
      completed: false,
      icon: 'BarChart2',
    },
  ],
  flowCategories: [
    {
      id: 'doctorReady',
      label: 'Doctor Ready',
      count: 2,
      isBottleneck: true,
    },
    {
      id: 'pendingInsurance',
      label: 'Pending Insurance',
      count: 24,
      isBottleneck: false,
    },
  ],
  wins: [
    {
      id: 'win1',
      title: 'Schedule optimized',
      description: 'Saved est. $1,240 via schedule optimization',
      savings: 1240,
      timestamp: '6:00 AM',
      icon: 'Calendar',
      isAi: true,
      timeSavedMin: 65,
    },
    {
      id: 'win2',
      title: 'Appointment filled',
      description: 'Last-minute cancellation filled with crown prep',
      value: 1250,
      timestamp: 'Yesterday',
      icon: 'Calendar',
      isAi: true,
      timeSavedMin: 20,
    },
    {
      id: 'win3',
      title: 'Collection improved',
      description: 'A/R > 90 days reduced by 8% this week',
      timestamp: 'This week',
      icon: 'TrendingDown',
      isAi: false,
    },
    {
      id: 'win4',
      title: 'Hygiene recall predicted',
      description: 'Projected 7% Q3 decline flagged for action',
      timestamp: '5:30 AM',
      icon: 'Activity',
      isAi: true,
      timeSavedMin: 30,
    },
    {
      id: 'win5',
      title: 'Performance insights',
      description: 'Optimized staffing saved $320 yesterday',
      timestamp: '6:45 AM',
      savings: 320,
      icon: 'Users',
      isAi: true,
      timeSavedMin: 45,
    },
  ],
};

export const roleBasedData: Record<UserRole, DashboardData> = {
  frontOffice: frontOfficeData,
  hygienist: hygienistData,
  provider: providerData,
  billing: billingData,
  owner: ownerData,
};